version: '3.8'

services:
  ixrlibforwebxr:
    container_name: ixrlibforwebxr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3999:3999" # Expose the debugging port
    networks:
      - frontend
    restart: always
    env_file:
      - .env
    command: ["--debug"]
    volumes:
      - .:/opt/informxr

networks:
  frontend: {}
  backend: {}
